import turtle
t=turtle.Turtle()
t.shape("turtle")
t.shapesize(2)
t.color("green")
t.forward(100)
t.left(90)
t.color("red")
t.forward(200)
t.left(90)
t.color("blue")
t.forward(100)
t.left(90)
t.color("pink")
t.forward(200)
t.left(90)
